Update abseil-cpp version in top_level_CMakeLists.txt to restore testing.
It is unclear what exactly broke testing with the standard command:

```
./scripts/google_run_tests.sh --make_jobs=48
```

```
/usr/local/google/home/rwgk/tmp/pybind11_abseil/tmp_build/_deps/abseil-cpp-src/absl/strings/internal/str_format/extension.h:34:6: warning: elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword
   34 | enum class FormatConversionChar : uint8_t;
      | ~~~~ ^~~~~
      |      -----
/usr/local/google/home/rwgk/tmp/pybind11_abseil/tmp_build/_deps/abseil-cpp-src/absl/strings/internal/str_format/extension.h:34:33: error: found ‘:’ in nested-name-specifier, expected ‘::’
   34 | enum class FormatConversionChar : uint8_t;
      |                                 ^
      |                                 ::
```

Updating abseil-cpp to the same version as used in the bazel WORKSPACE file fixes the cmake build failures.

PiperOrigin-RevId: 574639457